# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sitzungsprotokolle der FSI Lehramt MINT
author:
    name: FSI Lehramt MINT
    email: fsi-lehramt-mint@fau.de
description: >- # this means to ignore newlines until "baseurl:"
  Auf dieser Seite sammeln wir seit dem 16.10.2024 unsere Sitzungsprotokolle.
  Diese erscheinen im Rahmen eines Blogs, den man auch per RSS-Feed abonnieren
  kann.
baseurl: "/Protokolle" # the subpath of your site, e.g. /blog
url: "https://fsi-la-mint.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: fsi-la-mint

# Build settings
#theme: minima
remote_theme: jekyll/minima
minima:
  skin: auto
  date_format: "%A, %d.%m.%Y"
  social_links:
     - title: Unsere Website
       icon: skyatlas
       url: "https://lehramt-mint.fsi.fau.de/"
     - title: Unsere GitHub-Seite
       icon: github
       url: "https://github.com/fsi-la-mint"
titles_from_headings:
  enabled: false
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
